// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrfkViy_V4EsM43JSYw2eMaNpr6fI4G8',
    appId: '1:881961141773:web:b6f9dc31939347843b7744',
    messagingSenderId: '881961141773',
    projectId: 'kolo-292ad',
    authDomain: 'kolo-292ad.firebaseapp.com',
    storageBucket: 'kolo-292ad.firebasestorage.app',
    measurementId: 'G-8SEPQQX2KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpY9vt4BImtL9EzYCwAsegq3_7kmLOl3k',
    appId: '1:881961141773:android:30f79e9eb054b5573b7744',
    messagingSenderId: '881961141773',
    projectId: 'kolo-292ad',
    storageBucket: 'kolo-292ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARoviJ6pJN2KfUytVPKZ7_eHLC4RiYRJI',
    appId: '1:881961141773:ios:7982fb13199aac203b7744',
    messagingSenderId: '881961141773',
    projectId: 'kolo-292ad',
    storageBucket: 'kolo-292ad.firebasestorage.app',
    iosBundleId: 'com.micah.kolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARoviJ6pJN2KfUytVPKZ7_eHLC4RiYRJI',
    appId: '1:881961141773:ios:8c7d9dc81cd45ab43b7744',
    messagingSenderId: '881961141773',
    projectId: 'kolo-292ad',
    storageBucket: 'kolo-292ad.firebasestorage.app',
    iosBundleId: 'com.example.kolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrfkViy_V4EsM43JSYw2eMaNpr6fI4G8',
    appId: '1:881961141773:web:a9088ca00d75cb543b7744',
    messagingSenderId: '881961141773',
    projectId: 'kolo-292ad',
    authDomain: 'kolo-292ad.firebaseapp.com',
    storageBucket: 'kolo-292ad.firebasestorage.app',
    measurementId: 'G-Q9H3YDE9QY',
  );
}
